name: Feature request
description: Suggest an idea
title: ''
labels: ''
assignees: ''

- type: textarea
  attributes:
    label: Problem Description
    description: |
      A clear and concise description of what the problem is. For example, "I'm always frustrated when..."

- type: textarea
  attributes:
    label: Solution Description
    description: |
      A clear and concise description of what you want to happen.

- type: textarea
  attributes:
    label: Alternative Solutions
    description: |
      A clear and concise description of any alternative solutions or features you've considered.

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the feature request here.
